eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
okta:
  oauth2:
    issuer: https://dev-43344483.okta.com/oauth2/default
    audience: api://default
